namespace AutoFixture.Community.FSharp
open System
open AutoFixture.Xunit2

/// 
/// Provides auto-generated data specimens generated by AutoFixture as an extension to
/// xUnit.net's Theory attribute. 
/// 
/// Supports F#-specific types and function signatures.
/// 
[<Sealed>]
[<AttributeUsage(AttributeTargets.Method)>]
type AutoDataFSharpAttribute() =
    inherit AutoDataAttribute(fun () -> fsFixture)
    
/// 
/// Provides a data source for a data theory, with the data coming from inline
/// values combined with auto-generated data specimens generated by AutoFixture.
/// 
/// Supports F#-specific types and function signatures.
/// 
[<Sealed; AttributeUsage(AttributeTargets.Method, AllowMultiple = true)>]
type InlineAutoDataFSharpAttribute([<ParamArray>] values: obj[]) =
    inherit InlineAutoDataAttribute(AutoDataFSharpAttribute(), values)
